apiVersion: v1
kind: Secret
metadata:
  namespace: pruebaspierre
  name: api-access-token
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token